#!/bin/sh

[ -f /etc/wireguard/wg0.conf ] || exit 0

[ -x /usr/bin/wg-quick ] || exit 0

case "$1" in
    start)
        echo "Starting wireguard"
        /usr/bin/wg-quick up wg0
        ;;

    stop)
        echo "Stopping wireguard"
        /usr/bin/wg-quick down wg0
        ;;

    restart)
        echo "Restarting wireguard"
        /usr/bin/wg-quick down wg0
        sleep 2
        /usr/bin/wg-quick up wg0
        ;;
esac

exit 0
