#!/bin/sh

if [ ! -f /etc/firewall.rules ]; then
    exit 0
fi

case "$1" in
    start)
        echo "Starting firewall"
        iptables-restore < /etc/firewall.rules
        ;;

    stop)
        echo "Stopping firewall"
        iptables -F
        iptables -P INPUT ACCEPT
        iptables -P FORWARD DROP
        ;;

    restart)
        echo "Restarting firewall"
        iptables -F
        iptables-restore < /etc/firewall.rules
        ;;

    *)
        echo "Usage: firewall { start | stop | restart }"
        ;;
esac

exit 0

